development:
  adapter: mysql
  database: shop_development
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: shop_test
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql
  database: shop
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock
